LibrarySys/Controllers/BorrowController.cs
using LibrarySys.Models.Entity;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibrarySys.Controllers
{
    public class BorrowController : Controller
    {
        // GET: Borrow
        LibSysEntities db = new LibSysEntities();
        public ActionResult Index(string s, int page = 1)
        {
            var index = from b in db.ReaderBorrows.Where(x => x.Process == false) select b;
            if (!string.IsNullOrEmpty(s))
            {
                index = index.Where(m => m.Book.Title.Contains(s)||
                 m.Employee.LastName.Contains(s)||
                 m.Employee.FirstName.Contains(s)||
                 m.Reader.LastName.Contains(s)||
                 m.Reader.FirstName.Contains(s)||
                  m.Book.Author.LastName.Contains(s)||
                  m.Book.Author.FirstName.Contains(s)||
                  m.CheckoutDate.ToString().Contains(s) ||
                  m.ReturnDate.ToString().Contains(s)
                );

            }
            return View(index.ToList().ToPagedList(page, 6));
        }
        public ActionResult Archive(string s, int page = 1)
        {
            var index = from b in db.ReaderBorrows.Where(b => b.Process == true) select b;
            if (!string.IsNullOrEmpty(s))
            {
                index = index.Where(m => m.Book.Title.Contains(s)
                 ||  m.ID_employee.ToString().Contains(s)
                 ||  m.ID_reader.ToString().Contains(s)
                 ||  m.Reader.LastName.Contains(s)
                 ||  m.Reader.FirstName.Contains(s)
                 ||  m.Employee.LastName.Contains(s)
                 ||  m.Employee.FirstName.ToString().Contains(s)
                 ||  m.CheckoutDate.ToString().Contains(s)
                  || m.ReturnReader.ToString().Contains(s)
                );
            }
            return View(index.ToList().ToPagedList(page, 6));

        }

        [HttpGet]
        public ActionResult Borrow()
        {
            List<SelectListItem> reader = (from x in db.Readers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.FirstName + " " + x.LastName,
                                               Value = x.ID_reader.ToString()
                                           }).ToList();
            List<SelectListItem> book = (from y in db.Books.Where(x => x.Available == true).ToList()
                                         select new SelectListItem
                                         {
                                             Text = y.Title + " " + y.Author.FirstName + " " + y.Author.LastName,
                                             Value = y.ID_book.ToString()
                                         }).ToList();

            List<SelectListItem> employee = (from z in db.Employees.ToList()
                                             select new SelectListItem
                                             {
                                                 Text = z.FirstName + " " + z.LastName,
                                                 Value = z.ID_employee.ToString()
                                             }).ToList();
            ViewBag.r = reader;
            ViewBag.b = book;
            ViewBag.e = employee;
            return View();
        }
        [HttpPost]
        public ActionResult Borrow(ReaderBorrow p)
        {

            var d1 = db.Readers.Where(x => x.ID_reader == p.Reader.ID_reader).FirstOrDefault();
            var d2 = db.Books.Where(y => y.ID_book == p.Book.ID_book).FirstOrDefault();
            var d3 = db.Employees.Where(z => z.ID_employee == p.Employee.ID_employee).FirstOrDefault();
            p.Reader = d1;
            p.Book = d2;
            p.Employee = d3;
            db.ReaderBorrows.Add(p);
            db.SaveChanges();
           
            return RedirectToAction("Index");
        }

        public ActionResult ReaderReturn(int ID)
        {
            var odn = db.ReaderBorrows.Find(ID);
            DateTime d1 = DateTime.Parse(odn.ReturnDate.ToString());         
            DateTime d2 = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            TimeSpan d3 = d2 - d1;            //разликата между датата на която трябва да се върне книгата и която е била върната
            ViewBag.dgr = d3.TotalDays; 
            return View("ReaderReturn", odn);
        }
        public ActionResult Update(ReaderBorrow p)
        {
            var hrk = db.ReaderBorrows.Find(p.ID_borrow);
            hrk.ID_book = p.ID_book;
            hrk.ID_reader = p.ID_reader;
            hrk.ID_employee = p.ID_employee;
            hrk.ReturnReader = p.ReturnReader;
            hrk.ReturnReader = p.ReturnReader;
            hrk.Process = p.Process;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

LibrarySys/Views/Borrow/Archive.cshtml
@using LibrarySys.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList<ReaderBorrow>
@{
    ViewBag.Title = "Archive";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>
    <section class="main-content">
        <div class="container">

            <h1 style="text-align:center; font-style:italic"> Регистър на върнати книги </h1>

            @using (Html.BeginForm("Archive", "Borrow", FormMethod.Get))
            {
                <div style="margin-bottom:15px; margin-top:15px">
                    <ion-icon name="search-outline">   </ion-icon> &nbsp @Html.TextBox("s")
                    <input type="submit" value="Търсене" class="btn btn-primary btn-sm" />
                </div>
            }

            <table class="table">
                <thead>
                    <tr>

                        <th> # </th>
                        <th> Заглавие </th>
                        <th> Читател </th>
                        <th>  Служител </th>
                        <th> Дата на заемане на книга </th>
                        <th> Дата на връщане на книга  </th>
                        <th> Детайли </th>


                    </tr>
                </thead>

                @foreach (var bb in Model)
                {
                    <tbody>
                        <tr>
                            <td> @bb.ID_borrow </td>
                            <td> @bb.ID_book </td>
                            <td> @bb.Reader.FirstName &nbsp @bb.Reader.LastName</td>
                            <td> @bb.Employee.FirstName &nbsp @bb.Employee.LastName </td>
                            <td> @Convert.ToDateTime(bb.CheckoutDate).ToString("dd/MM/yyyy") </td>
                            <td> @Convert.ToDateTime(bb.ReturnReader).ToString("dd/MM/yyyy") </td>

                            <td>
                                <a href="~/Borrow/ReturnBook/@bb.ID_borrow" class="btn btn-primary btn-sm"> Детайли </a>
                            </td>

                        </tr>
                    </tbody>
                }

            </table>
        </div>
    </section>
    <div>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Archive", new { page }))
    </div>
</body>

</html>





<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/table style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

LibrarySys/Views/Borrow/Borrow.cshtml
@model LibrarySys.Models.Entity.ReaderBorrow
@{
    ViewBag.Title = "Borrow";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>

    <div class="content">

        <div class="container">
            <div class="row align-items-stretch no-gutters input-wrap">
                <div class="col-md-12">
                    <div class="form h-100">
                        <h3 style="text-align:center; font-style:italic; color:grey">Създай заявка</h3>

                        <form class="mb-5" method="post" id="inputForm" name="inputForm">
                            *<div class="row">
                                <div class="col-md-12 form-group mb-3">
                                    <label for="" class="col-form-label">Книга: *</label>
                                    @Html.DropDownListFor(k => k.Book.ID_book, (List<SelectListItem>)ViewBag.b, new { @class = "form-control", @placeholder = "Въведи името на книгата" })
                                    @Html.ValidationMessageFor(k => k.Book.ID_book, "", new { @style = "color:red" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Име на читателя: *</label>

                                    @Html.DropDownListFor(k => k.Reader.ID_reader, (List<SelectListItem>)ViewBag.r, new { @class = "form-control", @placeholder = "Избери читателя" })
                                    @Html.ValidationMessageFor(k => k.Reader.ID_reader, "", new { @style = "color:red" })
                                </div>

                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Служител: *</label>
                                    @Html.DropDownListFor(k => k.Employee.ID_employee, (List<SelectListItem>)ViewBag.e, new { @class = "form-control", @placeholder = "Избери служителя" })
                                    @Html.ValidationMessageFor(k => k.Employee.ID_employee, "", new { @style = "color:red" })

                                </div>

                            </div>

                            <div class="row">


                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Дата на заемане:* <input type="text" class="none" name="CheckOutDate" value="@DateTime.Now.ToShortDateString()" /></label>

                                </div>

                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Препоръчителна дата на връщане:* <input type="text" class="none" name="ReturnDate"  value="@DateTime.Now.AddDays(10).ToShortDateString()"/></label>

                                </div>

                            </div>

                            <input type="hidden" value="false" name="Process" />

                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <input type="submit" value="Добави" class="btn btn-primary rounded-0 py-2 px-4">
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>




</body>
</html>


<link href="~/Content/style_inputs.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Content/Panel/docs/assets/plugins/popper/esm/popper.min.js"></script>
<script src="~/Content/main_input.js"></script>
<style>
    label .none {
        border-style: none;
        font-size: 14px;
        color: #b3b3b3;
        margin: 0 0 10px 0;
    }
</style>

LibrarySys/Views/Borrow/Index.cshtml
@using LibrarySys.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList<ReaderBorrow>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>

    <section class="main-content">
        <div class="container">
            <h2 style="text-align:center; font-style:italic"> Регистър на активни  </h2>

            @using (Html.BeginForm("Index", "Borrow", FormMethod.Get))
            {
                <div style="margin-bottom:15px; margin-top:15px">
                    <ion-icon name="search-outline">   </ion-icon> &nbsp @Html.TextBox("s")
                    <input type="submit" value="Търсене" class="btn btn-primary btn-sm" />
                </div>
            }

            <table class="table">
                <thead>
                    <tr>
                        <th># </th>
                        <th>Книтага</th>
                        <th>Читател</th>
                        <th>Служител</th>
                        <th>Дата на заемане</th>

                        <th>Върни</th>
                    </tr>
                </thead>



                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>@item.ID_borrow</td>
                            <td>@item.Book.Title &nbsp; @item.Book.Author.FirstName &nbsp; @item.Book.Author.LastName</td>
                            <td>@item.Reader.FirstName &nbsp; @item.Reader.LastName</td>
                            <td>@item.Employee.FirstName &nbsp; @item.Employee.LastName</td>
                            <td>@Convert.ToDateTime(item.CheckoutDate).ToString("dd/MM/yyyy")</td>

                            <td>
                                <a href="~/Borrow/ReaderReturn/@item.ID_borrow" class="btn btn-primary btn-sm">Върни</a>
                            </td>

                        </tr>
                    </tbody>
                }


            </table>

        </div>

    </section>
    <div>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))
    </div>



</body>

</html>





<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/table style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

LibrarySys/Views/Borrow/ReaderReturn.cshtml
@model LibrarySys.Models.Entity.ReaderBorrow
@{
    ViewBag.Title = "ReaderReturn";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>
    <div class="content">
        <div class="container">
            <div class="row align-items-stretch no-gutters input-wrap">
                <div class="col-md-12">
                    <div class="form h-100">
                        <h3 style="text-align:center; font-style:italic; color:grey"> Одобри връщането на книгата</h3>
                        @using (Html.BeginForm("Update", "Borrow", FormMethod.Post))
                        {

                        <form class="mb-5" method="post" id="inputForm" name="inputForm">

                            <div class="row">
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label"> Заявка №: @Html.TextBoxFor(k => k.ID_borrow, new { @class = "none" })</label>
                                </div>
                                <div class="col-md-6 form-group mb-3">

                                    <label for="" class="col-form-label"> Заявка №: @Html.TextBoxFor(k => k.ID_book, new { @class = "none" })</label>
                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md-6 form-group mb-3">

                                    <label for="" class="col-form-label"> Служител ИД: @Html.TextBoxFor(k => k.ID_employee, new { @class = "none" })</label>
                                </div>
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label"> Читател ИД: @Html.TextBoxFor(k => k.ID_reader, new { @class = "none" })</label>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Дата на заемане:*    @Html.TextBoxFor(k => k.CheckoutDate, "{0:dd.MM.yyyy}", new { @class = "none" })</label>

                                </div>
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Дата на заемане:*    @Html.TextBoxFor(k => k.ReturnDate, "{0:dd.MM.yyyy}", new { @class = "none" })</label>

                                </div>
                            </div>

                            <div class="row">

                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Дата на връщане от читател:* <input type="text" class="none" name="ReturnReader" value="@DateTime.Now.ToShortDateString()" /></label>

                                </div>
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label"> Закъснение: @ViewBag.drg </label>
                                </div>


                            </div>
                            <input type="hidden" value="true" name="Process" />
                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <input type="submit" value="Одобри" class="btn btn-primary rounded-0 py-2 px-4">
                                </div>
                            </div>
                        </form>


                        }
                    </div>
                </div>

            </div>
        </div>
    </div>

</body>
</html>


<style>
    label .none {
        border-style: none;
        font-size: 14px;
        color: #b3b3b3;
        margin: 0 0 10px 0;
    }
</style>
<link href="~/Content/style_inputs.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Content/Panel/docs/assets/plugins/popper/esm/popper.min.js"></script>
<script src="~/Content/main_input.js"></script>