LibrarySys/Controllers/ReaderController.cs
using LibrarySys.Models.Entity;
using PagedList;
using Scrypt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibrarySys.Controllers
{
    public class ReaderController : Controller
    {
        // GET: Reader
        LibSysEntities db = new LibSysEntities();
        public ActionResult Index(string s, int page = 1)
        {

            var index = from b in db.Readers.Where(x => x.Activate ==true) select b;
            if (!string.IsNullOrEmpty(s))
            {

                index = index.Where(m => m.FirstName.Contains(s)
                || m.LastName.Contains(s)
                || m.Email.Contains(s)
                || m.School.Contains(s)
                || m.PhoneNumber.Contains(s));

            }
            return View(index.ToList().ToPagedList(page, 6));
        }

        public ActionResult Passive(string s, int page = 1)
        {

            var index = from b in db.Readers.Where(x => x.Activate == false) select b;
            if (!string.IsNullOrEmpty(s))
            {

                index = index.Where(m => m.FirstName.Contains(s)
                || m.LastName.Contains(s)
                || m.Email.Contains(s)
                || m.School.Contains(s)
                || m.PhoneNumber.Contains(s));

            }
            return View(index.ToList().ToPagedList(page, 6));
        }

        public ActionResult ActivateReader(int ID)
        {
            var delete = db.Readers.Find(ID);
            delete.Activate = true;
            // db.Readers.Remove(delete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddReader()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddReader(Reader r)
        {
            if (!ModelState.IsValid)
            {
                return View("AddReader");
            }
            ScryptEncoder encoder = new ScryptEncoder();
            Reader userItems = new Reader();
            string hashedPassword = encoder.Encode("Password");
            userItems.Email = r.Email;
            userItems.Activate = true;
            userItems.School = r.School;
            userItems.PhoneNumber = r.PhoneNumber;
            userItems.LastName = r.LastName;
            userItems.FirstName = r.FirstName;
            userItems.Password = hashedPassword;
            db.Readers.Add(userItems);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult DeleteReader(int ID)
        {
            var delete = db.Readers.Find(ID);
            delete.Activate = false;
            // db.Readers.Remove(delete);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UpdateReaderPage(int ID)
        {
            List<SelectListItem> activate = new List<SelectListItem>() {
        new SelectListItem { Text = "Активирай", Value = "true" },new SelectListItem {   Text = "Деакнивирай", Value = "false" }};
            ViewBag.act = activate;
            var update = db.Readers.Find(ID);
            return View("UpdateReaderPage", update);
        }

        public ActionResult UpdateReader(Reader r)
        {

            ScryptEncoder encoder = new ScryptEncoder();

          // var user = (string)Session["Email"];
            var userItems = db.Readers.Find(r.ID_reader);
            // bool areEquals = encoder.Compare("Password", hashPassword.ToString());
            //Reader userItems = new Reader();
            string hashedPassword = encoder.Encode("Password");
            userItems.School = r.School;
            userItems.PhoneNumber = r.PhoneNumber;
            userItems.LastName = r.LastName;
            userItems.FirstName = r.FirstName;
            userItems.Password = hashedPassword;

            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult Archive(int ID)
        {
            var book = db.ReaderBorrows.Where(x => x.ID_reader == ID).ToList();
            var reader = db.Readers.Where(y => y.ID_reader == ID).Select(z => z.FirstName + " " + z.LastName).FirstOrDefault();
            ViewBag.r = reader;
            return View(book);
        }
    }
}

LibrarySys/Views/Reader/AddReader.cshtml
@model LibrarySys.Models.Entity.Reader
@{
    ViewBag.Title = "AddReader";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>
    <div class="content">
        <div class="container">
            <div class="row align-items-stretch no-gutters input-wrap">
                <div class="col-md-12">
                    <div class="form h-100">
                        <h3 style="text-align:center; font-style:italic; color:grey">Добави Читател</h3>

                        <form class="mb-5" method="post" id="inputForm" name="inputForm">


                            <div class="row">
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Име *</label>
                                    @Html.TextBoxFor(r => r.FirstName, new { @class = "form-control", @placeholder = "Въведи името на читателя" })
                                    @Html.ValidationMessageFor(r => r.FirstName, "", new { @style = "color:red" })
                                </div>
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Фамилия  *</label>
                                    @Html.TextBoxFor(r => r.LastName, new { @class = "form-control", @placeholder = "Въведи фамилията на читателя" })
                                    @Html.ValidationMessageFor(r => r.LastName, "", new { @style = "color:red" })
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Имейл *</label>

                                    @Html.TextBoxFor(r => r.Email, new { @class = "form-control", @placeholder = "Въведи имейл" })
                                    @Html.ValidationMessageFor(r => r.Email, "", new { @style = "color:red" })

                                </div>
                                <div class="col-md-6 form-group mb-3">
                                    <label for="" class="col-form-label">Парола *</label>
                                    @Html.TextBoxFor(r => r.Password, new { @type = "password", @id = "pass", @class = "form-control", @placeholder = "Въведи парола" }) <input type="checkbox" onclick="showhide()" class="col-form-label" /> Покажи/Скрий парола
                                    @Html.ValidationMessageFor(r => r.Password, "", new { @style = "color:red" })


                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 form-group mb-3">
                                    <label for="" class="col-form-label">Телефонен номер *</label>

                                    @Html.TextBoxFor(r => r.PhoneNumber, new { @class = "form-control", @placeholder = "Въведи телефонен номер" })
                                    @Html.ValidationMessageFor(r => r.PhoneNumber, "", new { @style = "color:red" })
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12 form-group mb-3">
                                    <label for="" class="col-form-label">Учебно заведение *</label>
                                    @Html.TextBoxFor(r => r.School, new { @class = "form-control", @placeholder = "Въведи учебно заведение" })
                                    @Html.ValidationMessageFor(r => r.School, "", new { @style = "color:red" })
                                </div>

                            </div>


                            <div class="row">
                                <div class="col-md-12 form-group">
                                    <input type="submit" value="Добави" class="btn btn-primary rounded-0 py-2 px-4">
                                    <span class="submitting"></span>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>


<link href="~/Content/style_inputs.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Content/Panel/docs/assets/plugins/popper/esm/popper.min.js"></script>
<script src="~/Content/main_input.js"></script>

<script>
    function showhide() {
        var x = document.getElementById("pass");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>

LibrarySys/Views/Reader/Archive.cshtml
@using LibrarySys.Models.Entity
@model List<ReaderBorrow>
@{
    ViewBag.Title = "Archive";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>

    <section class="main-content">
        <div class="container">
            <h2 style="text-align:center" class="font-style:italic">@ViewBag.r</h2>
            <br />
            <table class=table>
                <thead>
                    <tr>
                        <th>Книга </th>
                        <th>Служител</th>
                        <th>Дата на заемане</th>
                        <th>Дата на връщане</th>
                    </tr>
                </thead>
                @foreach (var item in Model)
                {
                    <tbody>
                        <tr>
                            <td>@item.Book.ID_book &nbsp; @item.Book.Title - &nbsp; @item.Book.Author.FirstName&nbsp; @item.Book.Author.LastName </td>

                            <td>@item.Employee.ID_employee &nbsp; @item.Employee.FirstName &nbsp; @item.Employee.LastName</td>
                            <td>@Convert.ToDateTime(item.CheckoutDate).ToString("dd/MM/yyyy")</td>
                            <td>@Convert.ToDateTime(item.ReturnReader).ToString("dd/MM/yyyy")</td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
    </section>
</body>
</html>


<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/table style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

LibrarySys/Views/Reader/Index.cshtml
@using LibrarySys.Models.Entity
@using PagedList
@using PagedList.Mvc

@model PagedList.IPagedList<Reader>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>

    <section class="main-content">
        <div class="container">
            <h1 style="text-align:center; font-style:italic"> Читатели: </h1>

            @using (Html.BeginForm("Index", "Reader", FormMethod.Get))
            {
                <div style="margin-bottom:15px; margin-top:15px">
                    <ion-icon name="search-outline">   </ion-icon> &nbsp @Html.TextBox("s")
                    <input type="submit" value="Търсене" class="btn btn-primary btn-sm" />
                </div>
            }   <a href="~/Reader/Passive" class="btn btn-primary btn-sm" style="float:right;"> Не активни читатели </a>
            <table class="table">
                <thead>
                    <tr>
                        <th> ID </th>
                        <th> Име </th>
                        <th> Фамилия </th>
                        <th> Имейл </th>
                        <th> Телефонен номер </th>
                        <th> Училище </th>
                        <th> Архив </th>
                        <th> Действия </th>

                    </tr>
                </thead>
                @foreach (var r in Model)
                {
                    <tbody>
                        <tr>
                            <td> @r.ID_reader </td>
                            <td> @r.FirstName </td>
                            <td> @r.LastName</td>
                            <td> @r.Email</td>
                            <td> @r.PhoneNumber</td>
                            <td> @r.School</td>

                            <td>
                                <a href="~/Reader/Archive/@r.ID_reader" class="btn btn-primary btn-sm"> Книги </a>
                            </td>

                            <td>
                                <div class="dropdown open">
                                    <a href="#!" class="px-2" id="triggerId3" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">
                                        <i class="fa fa-ellipsis-v"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="triggerId3">

                                        <a class="dropdown-item" href="~/Reader/UpdateReaderPage/@r.ID_reader"><i class="fa fa-pencil mr-1"></i> Актуализиране</a>

                                        <a class="dropdown-item text-danger" href="~/Reader/DeleteReader/@r.ID_reader" onclick="return confirm('Потвърждавате ли че искате да деактивирате читателя')"><i class="fa fa-recycle mr-1"></i> Деактивирай </a>


                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
    </section>


    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

    <a href="~/Reader/AddReader" class="btn btn-primary btn-sm"> Добави </a> 
</body>
</html>


<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/table style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

LibrarySys/Views/Reader/Passive.cshtml
@using LibrarySys.Models.Entity
@using PagedList
@using PagedList.Mvc

@model PagedList.IPagedList<Reader>
@{
    ViewBag.Title = "Passive";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>

    <section class="main-content">
        <div class="container">
            <h1 style="text-align:center; font-style:italic"> Не активни читатели: </h1>

            @using (Html.BeginForm("Index", "Reader", FormMethod.Get))
            {
                <div style="margin-bottom:15px; margin-top:15px">
                    <ion-icon name="search-outline">   </ion-icon> &nbsp @Html.TextBox("s")
                    <input type="submit" value="Търсене" class="btn btn-primary btn-sm" />
                </div>
            }   <a href="~/Reader/Index" class="btn btn-primary btn-sm" style="float:right;"> Активни читатели </a>
            <table class="table">
                <thead>
                    <tr>
                        <th> ID </th>
                        <th> Име </th>
                        <th> Фамилия </th>
                        <th> Имейл </th>
                        <th> Телефонен номер </th>
                        <th> Училище </th>
                        <th> Архив </th>
                        <th> Действия </th>

                    </tr>
                </thead>
                @foreach (var r in Model)
                {
                    <tbody>
                        <tr>
                            <td> @r.ID_reader </td>
                            <td> @r.FirstName </td>
                            <td> @r.LastName</td>
                            <td> @r.Email</td>
                            <td> @r.PhoneNumber</td>
                            <td> @r.School</td>

                            <td>
                                <a href="~/Reader/Archive/@r.ID_reader" class="btn btn-primary btn-sm"> Книги </a>
                            </td>

                            <td>
                                <div class="dropdown open">
                                    <a href="#!" class="px-2" id="triggerId3" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">
                                        <i class="fa fa-ellipsis-v"></i>
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="triggerId3">

                                        <a class="dropdown-item" href="~/Reader/UpdateReaderPage/@r.ID_reader"><i class="fa fa-pencil mr-1"></i> Актуализиране</a>

                                        <a class="dropdown-item text-danger" href="~/Reader/ActivateReader/@r.ID_reader" onclick="return confirm('Потвърждавате ли че искате да активирате читателя')"><i class="fa fa-recycle mr-1"></i> Активирай </a>


                                    </div>
                                </div>
                            </td>
                        </tr>
                    </tbody>
                }
            </table>
        </div>
    </section>


    @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

</body>
</html>


<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/table style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

LibrarySys/Views/Reader/UpdateReaderPage.cshtml
@model LibrarySys.Models.Entity.Reader
@{
    ViewBag.Title = "UpdateReaderPage";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<html>
<body>

    <div class="content">

        <div class="container">
            <div class="row align-items-stretch no-gutters input-wrap">
                <div class="col-md-12">
                    <div class="form h-100">
                        <h3 style="text-align:center; font-style:italic; color:grey">Актуализиране на читател</h3>
                        @using (Html.BeginForm("UpdateReader", "Reader", FormMethod.Post))
                        {

                            <form class="mb-5" method="post" id="inputForm" name="inputForm">

                                <div class="row">
                                    <label for="" class="col-form-label"> ИД: @Html.TextBoxFor(r => r.ID_reader, new { @class = "none" })</label>
                                </div>


                                <div class="row">
                                    <div class="col-md-6 form-group mb-3">
                                        <label for="" class="col-form-label">Име: *</label>
                                        @Html.TextBoxFor(r => r.FirstName, new { @class = "form-control", @placeholder = "Въведи името на читателя" })
                                        @Html.ValidationMessageFor(r => r.FirstName, "", new { @style = "color:red" })
                                    </div>
                                    <div class="col-md-6 form-group mb-3">
                                        <label for="" class="col-form-label">Фамилия:  *</label>
                                        @Html.TextBoxFor(r => r.LastName, new { @class = "form-control", @placeholder = "Въведи фамилията на читателя" })
                                        @Html.ValidationMessageFor(r => r.LastName, "", new { @style = "color:red" })
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 form-group mb-3">
                                        <label for="" class="col-form-label">Имейл: *</label>

                                        @Html.TextBoxFor(r => r.Email, new { @class = "form-control", @placeholder = "Въведи имейл" })
                                        @Html.ValidationMessageFor(r => r.Email, "", new { @style = "color:red" })

                                    </div>
                                    <div class="col-md-6 form-group mb-3">
                                        <label for="" class="col-form-label">Парола: *</label>
                                        @Html.TextBoxFor(r => r.Password, new { @type = "password", @id = "pass", @class = "form-control", @placeholder = "Въведи парола" }) <input type="checkbox" onclick="showhide()" class="col-form-label" /> Покажи/Скрий парола
                                        @Html.ValidationMessageFor(r => r.Password, "", new { @style = "color:red" })


                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-6 form-group mb-3">
                                        <label for="" class="col-form-label">Телефонен номер: *</label>

                                        @Html.TextBoxFor(r => r.PhoneNumber, new { @class = "form-control", @placeholder = "Въведи телефонен номер" })
                                        @Html.ValidationMessageFor(r => r.PhoneNumber, "", new { @style = "color:red" })
                                    </div>

                                    <div class="col-md-6 form-group mb-3">
                                        <label for="" class="col-form-label"> Активирай/Деактивирай:  *</label>
                                        @Html.DropDownListFor(r => r.Activate, (List<SelectListItem>)ViewBag.act, new { @class = "form-control", @placeholder = "Избери" })
                                        @Html.ValidationMessageFor(r => r.Activate, "", new { @style = "color:red" })
                                    </div>

                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group mb-3">
                                        <label for="" class="col-form-label">Учебно заведение: *</label>
                                        @Html.TextBoxFor(r => r.School, new { @class = "form-control", @placeholder = "Въведи учебно заведение" })
                                        @Html.ValidationMessageFor(r => r.School, "", new { @style = "color:red" })
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="submit" value="Актуализирай" class="btn btn-primary rounded-0 py-2 px-4">
                                    </div>
                                </div>
                            </form>
                        }
                    </div>
                </div>

            </div>
        </div>
    </div>

</body>
</html>


<style>
    label .none {
        border-style: none;
        font-size: 14px;
        color: #b3b3b3;
        margin: 0 0 10px 0;
    }
</style>
<link href="~/Content/style_inputs.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Content/Panel/docs/assets/plugins/popper/esm/popper.min.js"></script>
<script src="~/Content/main_input.js"></script>


<script>
    function showhide() {
        var x = document.getElementById("pass");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }
</script>