LibrarySys/Controllers/ReaderPanelController.cs
using LibrarySys.Models.Entity;
using PagedList;
using Scrypt;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace LibrarySys.Controllers
{
    public class ReaderPanelController : Controller
    {
        // GET: ReaderPanel
        LibSysEntities db = new LibSysEntities();
        public ActionResult Index()
        {
            var email = (string)Session["Email"];
            var news = db.News.ToList();
            var d1 = db.Readers.Where(x => x.Email == email).Select(y => y.FirstName).FirstOrDefault();
            ViewBag.d1 = d1;
            var d2 = db.Readers.Where(x => x.Email == email).Select(y => y.LastName).FirstOrDefault();
            ViewBag.d2 = d2;
            var d4 = db.Readers.Where(x => x.Email == email).Select(y => y.School).FirstOrDefault();
            ViewBag.d4 = d4;
            var d5 = db.Readers.Where(x => x.Email == email).Select(y => y.PhoneNumber).FirstOrDefault();
            ViewBag.d5 = d5;
            var d6 = db.Readers.Where(x => x.Email == email).Select(y => y.Email).FirstOrDefault();
            ViewBag.d6 = d6;
            var readerid = db.Readers.Where(x => x.Email == email).Select(y => y.ID_reader).FirstOrDefault();
            var d7 = db.ReaderBorrows.Where(x => x.ID_reader == readerid).Count();
            ViewBag.d7 = d7;
            var d9 = db.News.Where(x => x.Screen == true).Count();
            ViewBag.d9 = d9;
            var index = db.News.Where(x => x.Screen == true).ToList();
            return View(news);
        }
        [HttpPost]
        public ActionResult Index2(Reader r)
        {
            ScryptEncoder encoder = new ScryptEncoder();

            var user = (string)Session["Email"];
            var userItems = db.Readers.FirstOrDefault(x => x.Email == user);
            string hashedPassword = encoder.Encode("Password");
            userItems.School = r.School;
            userItems.PhoneNumber = r.PhoneNumber;
            userItems.LastName = r.LastName;
            userItems.FirstName = r.FirstName;
            userItems.Password = hashedPassword;

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ReadedBooks()
        {
            var reader = (string)Session["Email"];
            var ID = db.Readers.Where(x => x.Email == reader.ToString()).Select(z => z.ID_reader).FirstOrDefault();
            var index = db.ReaderBorrows.Where(x => x.ID_reader == ID).ToList();
            return View(index);
        }
        public ActionResult NewsReader()
        {
            var news = db.News.ToList();
            return View(news);
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login", "LoginRegister");
        }
        public PartialViewResult Partial1()
        {
            var index = db.News.Where(x => x.Screen == true).ToList();
            return PartialView(index);
        }
        public PartialViewResult Partial2()
        {
            var user = (string)Session["Email"];
            var id = db.Readers.Where(x => x.Email == user).Select(y => y.ID_reader).FirstOrDefault();
            var find = db.Readers.Find(id);
            return PartialView("Partial2", find);
        }

        public ActionResult BooksSearch(string s, int page = 1)
        {
            var index = from b in db.Books select b;
            if (!string.IsNullOrEmpty(s))
            {

                index = index.Where(m => m.Title.Contains(s)
               || m.Author.FirstName.Contains(s)
               || m.Author.LastName.Contains(s)
               || m.Publisher.name.Contains(s)
               || m.Genre.name.Contains(s)
               || m.Year.Contains(s)
               || m.Pages.Contains(s));

            }
            return View(index.ToList().ToPagedList(page, 6));
        }
    }
}

LibrarySys/Views/ReaderPanel/BooksSearch.cshtml
@using LibrarySys.Models.Entity
@using PagedList
@using PagedList.Mvc

@model IEnumerable<Book>
@{
    ViewBag.Title = "BooksSearch";
    Layout = "~/Views/Shared/LayoutReader.cshtml";
}

<html>
<body>

    <section class="main-content">
        <div class="container">
            <h1 style="text-align:center; font-style:italic"> Книги </h1>
            <br />

            @using (Html.BeginForm("BooksSearch", "ReaderPanel", FormMethod.Get))
            {
                <div style="margin-bottom:15px; margin-top:15px">
                    <ion-icon name="search-outline">   </ion-icon> &nbsp @Html.TextBox("s")
                    <input type="submit" value="Търсене" class="btn btn-primary btn-sm" />
                </div>
            }
            <table class="table">
                <thead>
                    <tr>

                        <th> # </th>
                        <th> Заглавие </th>
                        <th> Автор </th>
                        <th>  Жанр</th>
                        <th> Година </th>
                        <th> Издателство </th>
                        <th> Страници </th>
                        <th> Брой </th>
                        <th> Наличност </th>

                    </tr>
                </thead>

                @foreach (var bk in Model)
                {
                    <tbody>
                        <tr>
                            <td> @bk.ID_book </td>
                            <td> @bk.Title </td>
                            <td> @bk.Author.FirstName&nbsp @bk.Author.LastName</td>
                            <td> @bk.Genre.name </td>
                            <td> @bk.Year </td>
                            <td> @bk.Publisher.name </td>
                            <td> @bk.Pages </td>
                            <td> @bk.Stock </td>
                            <td class=" text-center">
                                @if (@bk.Available == true)
                                {<span class="active-circle bg-success"></span> }
                                else
                                {<span class="active-circle bg-danger "></span>}
                            </td>

                        </tr>
                    </tbody>
                }
            </table>
        </div>
    </section>
    <div>
        @Html.PagedListPager((IPagedList)Model, page => Url.Action("BooksSearch", new { page }))
    </div>
</body>
</html>





<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="~/Content/PagedList.css" rel="stylesheet" />
<link href="~/Content/table style.css" rel="stylesheet" />
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

LibrarySys/Views/ReaderPanel/Index.cshtml
@using LibrarySys.Models.Entity
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutReader.cshtml";
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Читателски панел</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/Panel/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/Panel/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Navbar -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <!-- Profile Image -->
                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">
                            <div class="text-center">
                                <img class="profile-user-img img-fluid img-circle"
                                     src="@ViewBag.d3 " srcset="~/Content/profile.jpg"
                                     alt="User profile picture">
                            </div>
                            <p class="text-muted text-center">Читател: </p>
                            <h3 class="profile-username text-center">@ViewBag.d1 @ViewBag.d2</h3>

                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    <b>Книги:</b> <a class="float-right">@ViewBag.d7</a>
                                </li>

                                <li class="list-group-item">
                                    <b>Новини:</b> <a class="float-right">@ViewBag.d9</a>
                                </li>
                            </ul>
                            <a href="~/ReaderPanel/LogOut/" class="btn btn-primary btn-block"><b> Изход </b></a>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <!-- About Me Box -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">За нас</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <strong><i class="fas fa-book mr-1"></i> Училище </strong>
                            <p class="text-muted">
                                @ViewBag.d4
                            </p>
                            <hr>
                            <strong><i class="fas fa-map-marker-alt mr-1"></i>Телефон </strong>
                            <p class="text-muted">@ViewBag.d5</p>



                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-header p-2">
                            <ul class="nav nav-pills">
                                <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Новини</a></li>
                                <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Настройки</a></li>
                            </ul>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <div class="tab-content">
                                <div class="active tab-pane" id="activity">
                                    <!-- Post -->
                                    @Html.Partial("Partial1")
                                    <!-- /.post -->
                                </div>
                                <div class="tab-pane" id="settings">
                                    @Html.Action("Partial2", "ReaderPanel")
                                </div>
                            </div>

                        </div><!-- /.card-body -->
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/Content/Panel/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/Panel/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/Panel/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/Panel/dist/js/demo.js"></script>
</body>
</html>

LibrarySys/Views/ReaderPanel/Partial1.cshtml
@using LibrarySys.Models.Entity
@model List<News>

@foreach (var n in Model.Where(x => x.Screen == true).ToList())
{
    <div class="post">
        <div class="user-block">
            <img class="img-circle img-bordered-sm" src="~/Content/Panel/books.png" alt="user image">
            <span class="username">
                <a href="#">@n.Subject</a>
                <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>
            </span>
            <span class="description">@Convert.ToDateTime(n.Date).ToString("dd/MM/yyyy")</span>
        </div>
        <!-- /.user-block -->
        <p>
            @n.Article
        </p>
    </div>
}

LibrarySys/Views/ReaderPanel/Partial2.cshtml
@model LibrarySys.Models.Entity.Reader
@using (Html.BeginForm("Index2", "ReaderPanel", FormMethod.Post))
{
    <form class="form-horizontal">
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Име:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.FirstName, "", new { @style = "color:red" })

            </div>
        </div>
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Фамилия:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.LastName, "", new { @style = "color:red" })
            </div>
        </div>

        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Парола:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Password, new { @class = "form-control", @type = "password", @id = "pass" })  <input type="checkbox" onclick="showhide()" /> Покажи/Скрий парола
                @Html.ValidationMessageFor(x => x.Password, "", new { @style = "color:red" })
            </div>
        </div>
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Снимка:</label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.PhoneNumber, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.PhoneNumber, "", new { @style = "color:red" })
            </div>
        </div>
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Училище: </label>
            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.School, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.School, "", new { @style = "color:red" })
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-sm-2 col-sm-10">
                <button type="submit" class="btn btn-danger">Актуализиране </button>
            </div>
        </div>
    </form>
}


<script>
        function showhide() {
            var x = document.getElementById("pass");
            if (x.type === "password") {
                x.type = "text";
            } else {
                x.type = "password";
            }
        }
</script>

LibrarySys/Views/ReaderPanel/ReadedBooks.cshtml
@using LibrarySys.Models.Entity
@model List<ReaderBorrow>
@{
    ViewBag.Title = "ReadedBooks";
    Layout = "~/Views/Shared/LayoutReader.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- /.col -->
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header p-2">
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <div class="tab-pane" id="timeline">
                                <!-- The timeline -->
                                <div class="timeline timeline-inverse">
                                    <!-- timeline time label -->
                                    @foreach (var item in Model)
                                    {
                                        <div class="time-label">
                                            <a class="btn btn-success">
                                                <span class="bg-success">
                                                    @(((DateTime)item.CheckoutDate).ToString("dd-MMM-yyyy"))
                                                </span>
                                            </a>
                                            -----
                                            <a class="btn btn-warning">
                                                <span class="bg-warning">
                                                    @if (item.ReturnReader == null)
                                                    { item.ReturnReader = null; }
                                                    else
                                                    {
                                                        @(((DateTime)item.ReturnReader).ToString("dd-MMM-yyyy"))}
                                                </span>
                                            </a>
                                        </div>
                                        <!-- /.timeline-label -->
                                        <!-- timeline item -->
                                        <div>
                                            <div class="timeline-item">
                                                <div class="timeline-body">
                                                    @item.Book.Title - @item.Book.Author.FirstName @item.Book.Author.LastName
                                                </div>

                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div><!-- /.card-body -->
                </div>
                <!-- /.nav-tabs-custom -->
            </div>
            <!-- /.col -->
        </div>
    </section>
</body>
</html>